### ISSUE TITLE
ReactJS components stylesheet handling

### ISSUE THREAD

**Issue by ddewaele** [ddewaele/web-gpio-react#1]
Need a good way to deal with CSS files.

If I have a ReactJS component, I would like to include its css or scss file with it.
From within the component I would like to import it and use it.

Currently I just do this : 

I create the `Board.css` file that gets processed by webpack (raw loader ?)

``` css

.boardcontainer {
   border: 1px solid #DDDDDD;
   width: 200px;
   height: 200px;
   position: relative;
}
```

And in my component I simply reference whatever is in the CSS.

``` html
<div className="boardcontainer"></div>
```

where really I would like to do something like this 

``` js
import s from './Board.scss';

<div className={s.boardcontainer}>
```

I also added a dependency to `react-bootstrap` that doesn't ship with CSS files. So to include them I needed to do this :  

On my NodeJS server :

``` js
//server.js

const PUBLIC_PATH = path.join(__dirname, 'public');
app.use('/', require('express').static(PUBLIC_PATH));
```

In my `index.html` file :

``` html
<link rel="stylesheet" href="css/bootstrap-min.css"/>
```
